apiVersion: v1
kind: ReplicationController
metadata:
  name: python-deploy
spec:
  replicas: 2
  selector:
    app: python-anil
  template:
    metadata:
      name: python-anil
      labels:
        app: python-anil
    spec:
      containers:
      - name: python-anil-container
        image: anilbidari/python:v2
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: python-anil-lb
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: python-anil
  type: LoadBalancer
