---
- hosts: ip-172-31-25-108.ec2.internal
  become: true
  tasks:
  
   - name: deploy mysql-db
     ansible.builtin.command: oc project demo
     
   - name: deploy mysql-db
     ansible.builtin.command: oc new-app mysql MYSQL_USER=user MYSQL_PASSWORD=pass MYSQL_DATABASE=testdb -l db=mysql --name=ajay-mysql
   
   - name: list pods
     ansible.builtin.command: oc get pods 
